#ifndef _MYCLASSLIB_H
#define _MYCLASSLIB_H
#include "ZUtil.h"
#include "ZOperateRegedit.h"
#include "ZStatic.h"
#include "ZButton.h"
#include "ZCircleButton.h"
#include "ZPlayer.h"
#include "ZTimeSliderCtrl.h"
#include "ZVolumeSliderCtrl.h"
#include "ZTreeCtrl.h"
#include "ZSqlite3.h"
#include "ZPlayList.h"
#include "ZComboBox.h"
#include "ZTabCtrl.h"
#include "ZSetting.h"
#include "ZListCtrl.h"
#include "ZLrcListBox.h"
#endif